2021-06-02 13:01:07.868969: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
usage: train.py [-h] [--initial_epoch INITIAL_EPOCH] [--epochs EPOCHS]
                --train_file_pattern TRAIN_FILE_PATTERN
                [--train_batch_size TRAIN_BATCH_SIZE]
                [--train_steps TRAIN_STEPS]
                [--eval_file_pattern EVAL_FILE_PATTERN]
                [--eval_batch_size EVAL_BATCH_SIZE] [--eval_steps EVAL_STEPS]
                [--eval_freq EVAL_FREQ] [--eval_after_training] --pipeline
                {syntetic,tensorflow,dali_cpu,dali_gpu}
                [--multi_gpu [MULTI_GPU [MULTI_GPU ...]]] [--seed SEED]
                [--hparams HPARAMS] [--model_name MODEL_NAME]
                [--output OUTPUT] [--start_weights START_WEIGHTS]
                [--log_dir LOG_DIR] [--ckpt_dir CKPT_DIR]
train.py: error: unrecognized arguments: --xd
